OrdererOrgs:
  - Name: Orderer
    Domain: pds.example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: FoodAndCivilSupplies
    Domain: food.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: GodownWarehouse
    Domain: godown.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
